openapi: 3.0.5
info:
  version: '0.0.1'
  title:  API
  description: 'Change the description of your  API. Have a look [here](https://github.com/eriklenaerts/api-system/#/content/common/swagger-docs?id=info-object) for tips on writing good documentation.'
servers:
  - url: https://api..com/v1
    description: Production server (uses live data)
  - url: https://sandbox-api..com:8443/v1
    description: Sandbox server (uses test data)
paths:
  /items:
    get:
      description: Get all items from this wonderful API ;). 
      summary: Get all items
      responses:
        '200':
          description: OK
    post:
      description: Add a new item to the system.
      summary: Add a new item.
      responses:
        '200':
          description: OK
  /items/{id}:
    get:
      description: Retrieve a item for the given item id
      summary: Retrieve the data for one specific item
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: The item number.
          example: '<TODO: example here>'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/invoice'
        '404':
          description: Not Found
components:
  schemas:
    invoice:
      type: object
      properties:
        number: 
          type: string
          description: A unique sequential invoice number, prefixed with 'INV'
          example: INV10034
        date:
          type: string
          format: date
          description: The date when this invoice was issued.
          example: 28-04-2020
